### ISSUE TITLE
Issue with private route tables entries 

### ISSUE THREAD

**Issue by HarshitSF** [sourcefuse/terraform-aws-arc-network#70]
I am using custom subnet property to create private and public subnets.
In the private route table's routes, the entry of nat gateway ID is missing. NAt gateway is getting created and terraform apply is not giving any error. 
![Screenshot from 2024-01-31 21-36-52](https://github.com/sourcefuse/terraform-aws-arc-network/assets/69293204/02cbdbed-0015-4937-b3a1-c39a4ceb68a9)

source  = "sourcefuse/arc-network/aws"
version = "2.5.0"

here is the output of terraform apply - 
![image](https://github.com/sourcefuse/terraform-aws-arc-network/assets/69293204/be840f04-3104-43a2-9413-843ae531f45d)

here is tfvars file 

```
project_name             = "arc-saas"
environment              = "poc"
region                   = "us-west-2"
namespace                = "arc-saas"
vpc_cidr_block           = "10.0.0.0/16"
client_vpn_enabled       = false
is_custom_subnet_enabled = true

availability_zones = ["us-west-2a", "us-west-2b"]

# If is_custom_subnet_enabled variable is true then define these variable otherwise skip these

custom_private_subnet_ids = ["10.0.0.0/19", "10.0.64.0/19"]
custom_public_subnet_ids  = ["10.0.96.0/20", "10.0.112.0/20"]
``` 

``

**Comment by shubhamsinha-sf** [comment]
The problem is coming from here:

https://github.com/sourcefuse/terraform-aws-arc-network/blob/f8271748873d7613fb651459c09673706c0c00ad/modules/subnets/main.tf#L86-L94

the route is only considering the input variable for the list of nat gateways, however the code for creating the nat gateways is in the same module here:

https://github.com/sourcefuse/terraform-aws-arc-network/blob/f8271748873d7613fb651459c09673706c0c00ad/modules/subnets/main.tf#L172-L188

An idea solution would be to create a local and merge the two lists of nat gateways and then use that list as the iterator for the route in the private subnet routing table.
